name: Nikhil

on:
  push:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to User
        run: echo "Hello Nikhil"

      - name: say hello to Username
        run: echo "Hello $USER"
  deatils:
    runs-on: ubuntu-latest
    steps:
      - name: show all versionpython docker 
        run: docker --version && python --version
